services:
    db:
        image: postgres
        restart: always
        env_file:
            - .env
        ports:
            - "5432:5432"
        volumes:
            - db-data:/var/lib/postgresql/data
    app:
      image: abrasci_app
      entrypoint: ./entrypoint.sh
      build: .
      ports:
        - "8000:8000"
      depends_on:
        - db

volumes:
    db-data:
