"""create patient table

Revision ID: 672e4917e7f9
Revises: fb859d6fc3ba
Create Date: 2024-11-15 13:55:56.560897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '672e4917e7f9'
down_revision: Union[str, None] = 'fb859d6fc3ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('social_name', sa.String(), nullable=True),
    sa.Column('guardian_name', sa.String(), nullable=False),
    sa.Column('guardian_phone', sa.String(), nullable=False),
    sa.Column('idade', sa.Float(), nullable=False),
    sa.Column('auto_percepcao', sa.String(), nullable=False),
    sa.Column('suporte_social', sa.String(), nullable=False),
    sa.Column('condicoes_cronicas', sa.String(), nullable=False),
    sa.Column('medicamentos', sa.Integer(), nullable=False),
    sa.Column('internacoes', sa.Integer(), nullable=False),
    sa.Column('quedas', sa.String(), nullable=False),
    sa.Column('visao', sa.String(), nullable=False),
    sa.Column('audicao', sa.String(), nullable=False),
    sa.Column('limitacao_fisica', sa.String(), nullable=False),
    sa.Column('cognicao', sa.String(), nullable=False),
    sa.Column('humor', sa.String(), nullable=False),
    sa.Column('atividades_basicas', sa.String(), nullable=False),
    sa.Column('atividades_instrumentais', sa.String(), nullable=False),
    sa.Column('incontinencia', sa.String(), nullable=False),
    sa.Column('perda_peso', sa.String(), nullable=False),
    sa.Column('abandono', sa.String(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('patient')
    # ### end Alembic commands ###
