"""add observacoes to patient table

Revision ID: fb3b9c433786
Revises: 672e4917e7f9
Create Date: 2024-11-16 15:37:43.813846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb3b9c433786'
down_revision: Union[str, None] = '672e4917e7f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patient', sa.Column('observacoes', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patient', 'observacoes')
    # ### end Alembic commands ###
